# Generated by Django 2.0.3 on 2018-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('model_predicted', models.CharField(max_length=20)),
                ('google_prediction', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
